### PR TITLE
Ac3s rwild docker support

### PR DESCRIPTION
**Pull request by Ac3sRwild**
Had to change tag generation due to gigahorse versioning not being SemVer compliant. Also added docker usage info to the readme

### CODE REVIEW

**Comment by Ac3sRwild** [comment]
Max now that the fix is merged can you re-run the failed jobs under actions so that the docker images will be generated

**Comment by madMAx43v3r** [comment]
Ok triggered it

**Comment by madMAx43v3r** [comment]
Dang, fails again with:
`buildx failed with: ERROR: tag is needed when pushing to registry`

**Comment by madMAx43v3r** [comment]
I don't think it's using the new version...

**Pull request merged**
