### PR TITLE
Ac3s rwild docker support

### PR DESCRIPTION
**Pull request by Ac3sRwild**
Update images with more environment variables for easy configuration, add latest tags for gpu images, add Intel gpu support, update documentation with full working examples

### CODE REVIEW

**Comment by tjb-altf4** [comment]
@Ac3sRwild some additional documentation on advanced configuration options for Nvidia containers:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html
https://docs.docker.com/compose/gpu-support/

These resources would be mostly useful for configuring the exposed GPUs, say for example a specific GPU is to be used for farming.

**Comment by Ac3sRwild** [comment]
Yes those are excellent resources. I will have to read over them more and either just add the links or try to pull the most commonly used options out for use in the examples. I had already planned on refining the documentation further so this will help. For now though this should be good to go. I have tested on the current release as well as the giga15 and giga17 dev builds. Hopefully Max will merge this before the upcoming release so we new image builds ;)

**Comment by madMAx43v3r** [comment]
Is it ready for merging? I cannot test it myself...

**Comment by Ac3sRwild** [comment]
Yes it's good to go

**Pull request merged**
